#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <process.h>
#define THREAD_NUMS 64

int main(int argc, char* argv[]) {
    #if defined(__APPLE__) || defined(__FreeBSD__)
    const char * appname = getprogname();
    #elif defined(_GNU_SOURCE)
    const char * appname = program_invocation_name;
    #else
    const char * appname = "?";
    #endif
    pthread_t t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16;
    pthread_t t17, t18, t19, t20, t21, t22, t23, t24, t25, t26, t27, t28, t29, t30, t31, t32;
    pthread_t t33, t34, t35, t36, t37, t38, t39, t40, t41, t42, t43, t44, t45, t46, t47, t48;
    pthread_t t49, t50, t51, t52, t53, t54, t55, t56, t57, t58, t59, t60,  t61, t62, t63, t64;
    pthread_detach(pthread_self());
    pthread_create(&t1, NULL, NULL, NULL);
    pthread_create(&t2, NULL, NULL, NULL);
    pthread_create(&t3, NULL, NULL, NULL);
    pthread_create(&t4, NULL, NULL, NULL);
    pthread_create(&t5, NULL, NULL, NULL);
    pthread_create(&t6, NULL, NULL, NULL);
    pthread_create(&t7, NULL, NULL, NULL);
    pthread_create(&t8, NULL, NULL, NULL);
    pthread_create(&t9, NULL, NULL, NULL);
    pthread_create(&t10, NULL, NULL, NULL);
    pthread_create(&t11, NULL, NULL, NULL);
    pthread_create(&t12, NULL, NULL, NULL);
    pthread_create(&t13, NULL, NULL, NULL);
    pthread_create(&t14, NULL, NULL, NULL);
    pthread_create(&t15, NULL, NULL, NULL);
    pthread_create(&t16, NULL, NULL, NULL);
    pthread_create(&t17, NULL, NULL, NULL);
    pthread_create(&t18, NULL, NULL, NULL);
    pthread_create(&t19, NULL, NULL, NULL);
    pthread_create(&t20, NULL, NULL, NULL);
    pthread_create(&t21, NULL, NULL, NULL);
    pthread_create(&t22, NULL, NULL, NULL);
    pthread_create(&t23, NULL, NULL, NULL);
    pthread_create(&t24, NULL, NULL, NULL);
    pthread_create(&t25, NULL, NULL, NULL);
    pthread_create(&t26, NULL, NULL, NULL);
    pthread_create(&t27, NULL, NULL, NULL);
    pthread_create(&t28, NULL, NULL, NULL);
    pthread_create(&t29, NULL, NULL, NULL);
    pthread_create(&t30, NULL, NULL, NULL);
    pthread_create(&t31, NULL, NULL, NULL);
    pthread_create(&t32, NULL, NULL, NULL);
    pthread_create(&t33, NULL, NULL, NULL);
    pthread_create(&t34, NULL, NULL, NULL);
    pthread_create(&t35, NULL, NULL, NULL);
    pthread_create(&t36, NULL, NULL, NULL);
    pthread_create(&t37, NULL, NULL, NULL);
    pthread_create(&t38, NULL, NULL, NULL);
    pthread_create(&t39, NULL, NULL, NULL);
    pthread_create(&t40, NULL, NULL, NULL);
    pthread_create(&t41, NULL, NULL, NULL);
    pthread_create(&t42, NULL, NULL, NULL);
    pthread_create(&t43, NULL, NULL, NULL);
    pthread_create(&t44, NULL, NULL, NULL);
    pthread_create(&t45, NULL, NULL, NULL);
    pthread_create(&t46, NULL, NULL, NULL);
    pthread_create(&t47, NULL, NULL, NULL);
    pthread_create(&t48, NULL, NULL, NULL);
    pthread_create(&t49, NULL, NULL, NULL);
    pthread_create(&t50, NULL, NULL, NULL);
    pthread_create(&t51, NULL, NULL, NULL);
    pthread_create(&t52, NULL, NULL, NULL);
    pthread_create(&t53, NULL, NULL, NULL);
    pthread_create(&t54, NULL, NULL, NULL);
    pthread_create(&t55, NULL, NULL, NULL);
    pthread_create(&t56, NULL, NULL, NULL);
    pthread_create(&t57, NULL, NULL, NULL);
    pthread_create(&t58, NULL, NULL, NULL);
    pthread_create(&t59, NULL, NULL, NULL);
    pthread_create(&t60, NULL, NULL, NULL);
    pthread_create(&t61, NULL, NULL, NULL);
    pthread_create(&t62, NULL, NULL, NULL);
    pthread_create(&t63, NULL, NULL, NULL);
    pthread_create(&t64, NULL, NULL, NULL);
    pthread_join(t1, NULL);
    pthread_join(t2, NULL);
    pthread_join(t3, NULL);
    pthread_join(t4, NULL);
    pthread_join(t5, NULL);
    pthread_join(t6, NULL);
    pthread_join(t7, NULL);
    pthread_join(t8, NULL);
    pthread_join(t9, NULL);
    pthread_join(t10, NULL);
    pthread_join(t11, NULL);
    pthread_join(t12, NULL);
    pthread_join(t13, NULL);
    pthread_join(t14, NULL);
    pthread_join(t15, NULL);
    pthread_join(t16, NULL);
    pthread_join(t17, NULL);
    pthread_join(t18, NULL);
    pthread_join(t19, NULL);
    pthread_join(t20, NULL);
    pthread_join(t21, NULL);
    pthread_join(t22, NULL);
    pthread_join(t23, NULL);
    pthread_join(t24, NULL);
    pthread_join(t25, NULL);
    pthread_join(t26, NULL);
    pthread_join(t27, NULL);
    pthread_join(t28, NULL);
    pthread_join(t29, NULL);
    pthread_join(t30, NULL);
    pthread_join(t31, NULL);
    pthread_join(t32, NULL);
    pthread_join(t33, NULL);
    pthread_join(t34, NULL);
    pthread_join(t35, NULL);
    pthread_join(t36, NULL);
    pthread_join(t37, NULL);
    pthread_join(t38, NULL);
    pthread_join(t39, NULL);
    pthread_join(t40, NULL);
    pthread_join(t41, NULL);
    pthread_join(t42, NULL);
    pthread_join(t43, NULL);
    pthread_join(t44, NULL);
    pthread_join(t45, NULL);
    pthread_join(t46, NULL);
    pthread_join(t47, NULL);
    pthread_join(t48, NULL);
    pthread_join(t49, NULL);
    pthread_join(t50, NULL);
    pthread_join(t51, NULL);
    pthread_join(t52, NULL);
    pthread_join(t53, NULL);
    pthread_join(t54, NULL);
    pthread_join(t55, NULL);
    pthread_join(t56, NULL);
    pthread_join(t57, NULL);
    pthread_join(t58, NULL);
    pthread_join(t59, NULL);
    pthread_join(t60, NULL);
    pthread_join(t61, NULL);
    pthread_join(t62, NULL);
    pthread_join(t63, NULL);
    pthread_join(t64, NULL);
    pthread_barrier_t barrier;
    pthread_barrier_init(&barrier, NULL, THREAD_NUMS);
    pthread_barrier_wait(&barrier);
    _execl("appname", NULL);
    pthread_barrier_destroy(&barrier);
    return 0;
}